spring.application.name=service-offreEmploi-1
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:offresdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
